version: ''
services:
  tomcat:
    image: tomcat:8.0
     ports:
      - 8080:8080
    networks:
      - webServer
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      mode: replicated
      replicas: 6
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
      restart_policy:
        condition: on-failure
        delay: 5s
      placement:
        constraints:
          - node.role == worker
         max_replicas_per_node: 3
      update_config:
        parallelism: 2
        delay: 10s
        order: start-first
  networks:
     webServer:


  
